# Generated by Django 5.1.3 on 2024-12-01 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chef',
            name='bio',
        ),
    ]
